# Generated by Django 6.0.2 on 2026-02-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_forms_workflows", "0014_add_form_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaltask",
            name="stage_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stage number (1-indexed) for display purposes",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable stage name", max_length=100
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Execution order — lower numbers run first"
                    ),
                ),
                (
                    "approval_logic",
                    models.CharField(
                        choices=[
                            ("all", "All must approve (AND)"),
                            ("any", "Any can approve (OR)"),
                            ("sequence", "Sequential within stage"),
                        ],
                        default="all",
                        help_text="How approvals in this stage are resolved",
                        max_length=20,
                    ),
                ),
                (
                    "requires_manager_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Also require submitter's manager approval in this stage (requires LDAP)",
                    ),
                ),
                (
                    "approval_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that participate in this stage",
                        related_name="workflow_stages",
                        to="auth.group",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="django_forms_workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Stage",
                "verbose_name_plural": "Workflow Stages",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="approvaltask",
            name="workflow_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Stage this task belongs to (staged workflows only)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="django_forms_workflows.workflowstage",
            ),
        ),
    ]
