# Generated by Django 5.1 on 2026-02-20

from django.db import migrations, models

# Use IF NOT EXISTS so this migration is safe to run against a database
# where the column was already added manually (e.g. via direct SQL).
ADD_COLUMN_SQL = """
ALTER TABLE django_forms_workflows_formdefinition
    ADD COLUMN IF NOT EXISTS pdf_generation VARCHAR(20) NOT NULL DEFAULT 'none';
"""

DROP_COLUMN_SQL = """
ALTER TABLE django_forms_workflows_formdefinition
    DROP COLUMN IF EXISTS pdf_generation;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0015_add_workflowstage_staged_approvals"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=ADD_COLUMN_SQL,
                    reverse_sql=DROP_COLUMN_SQL,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="formdefinition",
                    name="pdf_generation",
                    field=models.CharField(
                        choices=[
                            ("none", "Disabled"),
                            ("anytime", "Anytime"),
                            ("post_approval", "Post Approval Only"),
                        ],
                        default="none",
                        help_text=(
                            "When a PDF of the submission can be downloaded. "
                            "'Anytime' allows download as soon as the form is submitted; "
                            "'Post Approval Only' restricts download to approved submissions."
                        ),
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]

