# Generated by Django 5.1 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0015_add_workflowstage_staged_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="pdf_generation",
            field=models.CharField(
                choices=[
                    ("none", "Disabled"),
                    ("anytime", "Anytime"),
                    ("post_approval", "Post Approval Only"),
                ],
                default="none",
                help_text=(
                    "When a PDF of the submission can be downloaded. "
                    "'Anytime' allows download as soon as the form is submitted; "
                    "'Post Approval Only' restricts download to approved submissions."
                ),
                max_length=20,
            ),
        ),
    ]

