# Generated by Django 5.2.7 on 2026-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0020_add_bulk_export_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingnotification",
            name="scheduled_for",
            field=models.DateTimeField(
                db_index=True,
                help_text="When this notification should be included in a batch send.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="notification_cadence",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate (send right away)"),
                    ("daily", "Daily digest"),
                    ("weekly", "Weekly digest"),
                    ("monthly", "Monthly digest"),
                    ("form_field_date", "On date from a form field"),
                ],
                default="immediate",
                help_text="When to send approval-request and submission notifications. Non-immediate options batch multiple notifications into a single digest email.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="notification_cadence_day",
            field=models.IntegerField(
                blank=True,
                help_text="For weekly: day of week (0=Monday … 6=Sunday). For monthly: day of month (1–31).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="notification_cadence_form_field",
            field=models.SlugField(
                blank=True,
                help_text="For 'On date from a form field': the field slug whose date value determines when to send the digest.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="notification_cadence_time",
            field=models.TimeField(
                blank=True,
                help_text="Time of day to send batch digest (leave blank to use 08:00).",
                null=True,
            ),
        ),
    ]
