# Generated by Django 5.2.7 on 2026-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0025_workflowstage_approve_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="width",
            field=models.CharField(
                choices=[
                    ("full", "Full Width"),
                    ("half", "Half Width"),
                    ("third", "One Third"),
                    ("fourth", "One Quarter"),
                ],
                default="full",
                max_length=10,
            ),
        ),
    ]
