# Generated by Django 5.2.7 on 2026-03-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_forms_workflows", "0027_formsubmission_form_data_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStageGroupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approve_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Custom approve button label for this group only (e.g. "Complete"). Overrides the stage\'s approve_label when set.',
                        max_length=100,
                    ),
                ),
                (
                    "hidden_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of field_names to hide from this group during approval (e.g. ["hr_completion_date"]). Hidden fields are not shown, not required, and not saved by this group.',
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_stage_configs",
                        to="auth.group",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_configs",
                        to="django_forms_workflows.workflowstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Group Config",
                "verbose_name_plural": "Stage Group Configs",
                "unique_together": {("stage", "group")},
            },
        ),
    ]
