# Generated by Django 5.2.7 on 2026-03-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0028_workflowstagegroupconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="workflow_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Stage this field appears in during approval. When set, takes precedence over the 'approval_step' integer and ties this field precisely to one stage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_fields",
                to="django_forms_workflows.workflowstage",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="approval_step",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy: approval step number this field belongs to (sequential workflows). For staged workflows prefer 'workflow_stage' FK instead.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="WorkflowStageGroupConfig",
        ),
    ]
