# Generated by Django 5.2.7 on 2026-03-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0032_approved_pending_detached_sub_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="subworkflowdefinition",
            name="reject_parent",
            field=models.BooleanField(
                default=False,
                help_text="When True, rejecting any sub-workflow instance immediately rejects the parent submission and cancels all other pending sub-workflows. When False (default), a rejected sub-workflow is treated as complete and the parent moves to 'Approved' once all instances are finished.",
            ),
        ),
        migrations.AlterField(
            model_name="subworkflowdefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subworkflowinstance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
