# Generated by Django 5.2.7 on 2026-03-11 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0033_add_reject_parent_to_subworkflowdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("submission_created", "Submission Received"),
                            ("approval_request", "Approval Request"),
                            ("approval_notification", "Approved"),
                            ("rejection_notification", "Rejected"),
                            ("approval_reminder", "Approval Reminder"),
                            ("escalation", "Escalation"),
                            ("batched", "Batched Digest"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="django_forms_workflows.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
