# Generated by Django 6.0.2 on 2026-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0035_migrate_prefill_source_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="auto_created",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="True when this stage was auto-created by the legacy-to-staged data migration.",
            ),
        ),
    ]

