# Generated by Django — removes legacy fields after data migration.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_forms_workflows", "0037_migrate_flat_workflows_to_staged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="prefill_source",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="approval_step",
        ),
    ]

