# Generated by Django 6.0.2 on 2026-03-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "django_forms_workflows",
            "0038_remove_legacy_prefill_source_and_approval_step",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="workflow_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Stage this field appears in during approval.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_fields",
                to="django_forms_workflows.workflowstage",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="approval_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED — use WorkflowStage.approval_groups instead. Flat-mode groups are auto-migrated to stages in migration 0037.",
                related_name="can_approve_workflows",
                to="auth.group",
            ),
        ),
    ]
