# Generated by Django 5.2.7 on 2026-03-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0040_migrate_deprecated_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="show_if_field",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="show_if_value",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="approval_groups",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="approval_logic",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="db_update_mappings",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="enable_db_updates",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="escalation_field",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="escalation_groups",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="escalation_threshold",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="manager_can_override_group",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="requires_manager_approval",
        ),
        migrations.RemoveField(
            model_name="workflowstage",
            name="auto_created",
        ),
    ]
