# Generated by Django 5.2.7 on 2026-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0041_remove_deprecated_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subworkflowdefinition",
            name="section_label",
            field=models.CharField(
                blank=True,
                help_text="Heading shown to end users in the approval history (e.g. 'Payment Approvals'). If blank, defaults to the sub-workflow form name.",
                max_length=100,
            ),
        ),
    ]
