# Generated by Django 5.2.7 on 2026-03-12 20:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0042_add_sub_workflow_section_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="form_data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="The actual form responses",
            ),
        ),
    ]
