# Generated by Django 6.0.2 on 2026-03-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0045_stageapprovalgroup_workflow_name_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowdefinition",
            name="form_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="django_forms_workflows.formdefinition",
            ),
        ),
    ]
