# Generated by Django 6.0.2 on 2026-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0046_workflow_definition_one_to_many"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowdefinition",
            name="hide_approval_history",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the submitter will not see approval history or individual approval steps — only the final decision (approved / rejected) is shown. Approvers and admins can still see the full history.",
            ),
        ),
    ]
