# Generated by Django 6.0.2 on 2026-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0047_add_hide_approval_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowdefinition",
            name="trigger_conditions",
            field=models.JSONField(
                blank=True,
                help_text='Conditions that must be met for this workflow to run. Format: {"operator": "AND|OR", "conditions": [{"field": "field_name", "operator": "equals|not_equals|gt|lt|gte|lte|contains|in", "value": "..."}]}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="trigger_conditions",
            field=models.JSONField(
                blank=True,
                help_text='Conditions that must be met for this stage to run. When advancing from a prior stage, only stages whose conditions match the submission data will be entered. Format: {"operator": "AND|OR", "conditions": [{"field": "field_name", "operator": "equals|not_equals|gt|lt|gte|lte|contains|in", "value": "..."}]}',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stageapprovalgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
