# Generated by Django 6.0.3 on 2026-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0059_add_multiselect_list_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstage",
            name="assignee_lookup_type",
            field=models.CharField(
                choices=[
                    ("email", "Email address"),
                    ("username", "Username (sAMAccountName)"),
                    ("full_name", "Full name (First Last)"),
                    ("ldap", "LDAP lookup by display name"),
                ],
                default="email",
                help_text="How to resolve the form field value to a system user. 'Email' looks up by email address. 'Username' looks up by sAMAccountName/username. 'Full name' matches against Django User first_name + last_name (iexact), then falls back to an LDAP search — NOTE: for Google SSO-only sites, first_name/last_name are only populated if Google SAML sends those attributes or users were pre-provisioned via sync_ldap_users. 'LDAP lookup' searches Active Directory directly by display name and auto-provisions the Django user if not yet in the system — recommended for sites where SSO does not populate first/last name.",
                max_length=20,
            ),
        ),
    ]
