# Generated by Django 5.2.7 on 2026-03-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0064_add_reviewer_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("submission_received", "Submission Received"),
                            ("approval_notification", "Submission Approved (final)"),
                            ("rejection_notification", "Submission Rejected (final)"),
                            ("withdrawal_notification", "Submission Withdrawn"),
                        ],
                        default="approval_notification",
                        help_text="Which workflow event triggers this notification.",
                        max_length=30,
                    ),
                ),
                (
                    "email_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Slug of the form field whose value is the recipient email address. Resolved from the submission's form_data at send time. Leave blank if you only need static recipients.",
                        max_length=200,
                    ),
                ),
                (
                    "static_emails",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of fixed email addresses to notify. Can be combined with Email Field to notify both static and dynamic addresses.",
                        max_length=1000,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom subject line. Leave blank to use the default for the event type. Supports {form_name} and {submission_id} placeholders.",
                        max_length=500,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        help_text="Optional conditions evaluated against form_data before sending. Same format as stage trigger_conditions. Leave blank to always send.",
                        null=True,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="django_forms_workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Notification",
                "verbose_name_plural": "Workflow Notifications",
                "ordering": ["id"],
            },
        ),
    ]
