# Generated by Django 5.2.7 on 2026-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0065_workflownotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflownotification",
            name="notify_submitter",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the person who submitted the form is always included as a recipient. Use this to replace the legacy 'notify on …' flags with a fully-configurable rule.",
            ),
        ),
    ]
