# Generated by Django 5.2.7 on 2026-03-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0067_migrate_legacy_notify_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="additional_notify_emails",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="notify_on_approval",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="notify_on_rejection",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="notify_on_submission",
        ),
        migrations.RemoveField(
            model_name="workflowdefinition",
            name="notify_on_withdrawal",
        ),
    ]
