# Generated by Django 6.0.3 on 2026-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0070_workflowstage_allow_edit_form_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submission_received", "Submission Received"),
                    ("approval_request", "Approval Request"),
                    ("approval_notification", "Approval Notification"),
                    ("rejection_notification", "Rejection Notification"),
                    ("withdrawal_notification", "Withdrawal Notification"),
                ],
                max_length=30,
            ),
        ),
    ]
