# Generated by Django 6.0.3 on 2026-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0072_add_change_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="notify_assignee_on_final_decision",
            field=models.BooleanField(
                default=False,
                help_text="Include this stage's dynamically-assigned approver as a recipient on final approval/rejection notifications. Only effective when assignee_form_field is set and a user was successfully resolved.",
            ),
        ),
    ]
