# Generated by Django 6.0.3 on 2026-03-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_forms_workflows", "0073_add_stage_notify_assignee_on_final_decision"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("submission_received", "Submission Received"),
                            ("approval_request", "Approval Request (stage activated)"),
                            (
                                "stage_decision",
                                "Stage Decision (individual stage completed)",
                            ),
                            ("workflow_approved", "Workflow Approved (final decision)"),
                            ("workflow_denied", "Workflow Denied (final decision)"),
                            ("form_withdrawn", "Form Withdrawn"),
                        ],
                        help_text="The workflow event that triggers this notification.",
                        max_length=30,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        help_text="Optional conditions evaluated against form_data. Uses the same format as stage trigger_conditions. When set, the notification only fires if conditions are met.",
                        null=True,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom email subject line. Supports {form_name} and {submission_id} placeholders. Leave blank for the default.",
                        max_length=500,
                    ),
                ),
                (
                    "notify_submitter",
                    models.BooleanField(
                        default=False,
                        help_text="Include the person who submitted the form.",
                    ),
                ),
                (
                    "email_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Form field slug whose submitted value is an email address. Resolved from form_data at send time (varies per submission).",
                        max_length=200,
                    ),
                ),
                (
                    "static_emails",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated fixed email addresses.",
                        max_length=1000,
                    ),
                ),
                (
                    "notify_stage_assignees",
                    models.BooleanField(
                        default=False,
                        help_text="Include dynamically-assigned approvers. When a stage is specified, only that stage's assignee is included. When no stage is specified, assignees from all stages are included.",
                    ),
                ),
                (
                    "notify_stage_groups",
                    models.BooleanField(
                        default=False,
                        help_text="Include all users in the stage's approval groups. When a stage is specified, only that stage's groups are included. When no stage is specified, groups from all stages are included.",
                    ),
                ),
                (
                    "notify_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional groups to notify, independent of stage assignment. All users in these groups with a non-empty email will receive the notification.",
                        related_name="notification_rules",
                        to="auth.group",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. When set, scopes this rule to a specific stage. Recipient sources like 'Notify stage assignees' and 'Notify stage groups' will reference only this stage. When blank, they reference all stages in the workflow.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to="django_forms_workflows.workflowstage",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to="django_forms_workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Rule",
                "verbose_name_plural": "Notification Rules",
                "ordering": ["workflow", "event", "stage"],
            },
        ),
    ]
