# Generated by Django 6.0.3 on 2026-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0075_migrate_to_notification_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submission_received", "Submission Received"),
                    ("approval_request", "Approval Request"),
                    ("stage_decision", "Stage Decision"),
                    ("workflow_approved", "Workflow Approved"),
                    ("workflow_denied", "Workflow Denied"),
                    ("form_withdrawn", "Form Withdrawn"),
                    ("approval_reminder", "Approval Reminder"),
                    ("escalation", "Escalation"),
                    ("batched", "Batched Digest"),
                    ("submission_created", "Submission Received (legacy)"),
                    ("approval_notification", "Approved (legacy)"),
                    ("rejection_notification", "Rejected (legacy)"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pendingnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submission_received", "Submission Received"),
                    ("approval_request", "Approval Request"),
                    ("stage_decision", "Stage Decision"),
                    ("workflow_approved", "Workflow Approved"),
                    ("workflow_denied", "Workflow Denied"),
                    ("form_withdrawn", "Form Withdrawn"),
                    ("approval_notification", "Approval Notification (legacy)"),
                    ("rejection_notification", "Rejection Notification (legacy)"),
                    ("withdrawal_notification", "Withdrawal Notification (legacy)"),
                ],
                max_length=30,
            ),
        ),
    ]
