# Generated by Django 6.0.3 on 2026-03-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0076_update_notification_event_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflownotification",
            name="workflow",
        ),
        migrations.RemoveField(
            model_name="workflowstage",
            name="notify_assignee_on_final_decision",
        ),
        migrations.DeleteModel(
            name="StageFormFieldNotification",
        ),
        migrations.DeleteModel(
            name="WorkflowNotification",
        ),
    ]
