# Generated by Django 6.0.3 on 2026-03-31 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0077_drop_legacy_notification_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for anonymous (public-form) submissions.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
