# Generated by Django 6.0.3 on 2026-04-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0078_allow_anonymous_submissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="HMAC signing secret. Leave blank to auto-generate a secure secret on save.",
                        max_length=255,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of subscribed event names, e.g. ['submission.created']",
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        help_text='Optional static headers as JSON, e.g. {"Authorization": "Bearer ..."}',
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=15)),
                ("retry_on_failure", models.BooleanField(default=True)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="django_forms_workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["workflow", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("submission.created", "Submission Created"),
                            ("submission.approved", "Submission Approved"),
                            ("submission.rejected", "Submission Rejected"),
                            ("submission.returned", "Submission Returned"),
                            ("task.created", "Approval Task Created"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "endpoint_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("delivery_url", models.URLField(max_length=500)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                (
                    "delivered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "approval_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_delivery_logs",
                        to="django_forms_workflows.approvaltask",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_delivery_logs",
                        to="django_forms_workflows.formsubmission",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_delivery_logs",
                        to="django_forms_workflows.workflowdefinition",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="django_forms_workflows.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery Log",
                "verbose_name_plural": "Webhook Delivery Logs",
                "ordering": ["-delivered_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "success"], name="django_form_event_3dadb8_idx"
                    ),
                    models.Index(
                        fields=["submission", "event"],
                        name="django_form_submiss_204b04_idx",
                    ),
                ],
            },
        ),
    ]
