# Generated by Django 5.2.7 on 2026-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0079_webhookendpoint_webhookdeliverylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="close_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Automatically stop accepting submissions after this date/time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="enable_captcha",
            field=models.BooleanField(
                default=False,
                help_text="Show a CAPTCHA challenge before submission. Requires FORMS_WORKFLOWS_CAPTCHA_SITE_KEY and FORMS_WORKFLOWS_CAPTCHA_SECRET_KEY in settings.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="max_submissions",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum total submissions allowed (leave blank for unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="one_per_user",
            field=models.BooleanField(
                default=False,
                help_text="Restrict each authenticated user to a single submission",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Single Line Text"),
                    ("phone", "Phone Number"),
                    ("textarea", "Multi-line Text"),
                    ("number", "Whole Number"),
                    ("decimal", "Decimal Number"),
                    ("currency", "Currency ($)"),
                    ("date", "Date"),
                    ("datetime", "Date and Time"),
                    ("time", "Time"),
                    ("email", "Email Address"),
                    ("url", "Website URL"),
                    ("select", "Dropdown Select"),
                    ("multiselect", "Multiple Select (Checkboxes)"),
                    ("multiselect_list", "Multiple Select (List)"),
                    ("radio", "Radio Buttons"),
                    ("checkbox", "Single Checkbox"),
                    ("checkboxes", "Multiple Checkboxes"),
                    ("file", "File Upload"),
                    ("multifile", "Multi-File Upload"),
                    ("hidden", "Hidden Field"),
                    ("section", "Section Header (not a field)"),
                    ("calculated", "Calculated / Formula"),
                    ("spreadsheet", "Spreadsheet Upload (CSV / Excel)"),
                    ("country", "Country Picker"),
                    ("us_state", "US State Picker"),
                    ("signature", "Signature"),
                    ("rating", "Rating (Stars)"),
                    ("matrix", "Matrix / Grid"),
                    ("address", "Address"),
                    ("slider", "Slider"),
                ],
                max_length=20,
            ),
        ),
    ]
