# Generated by Django 5.2.7 on 2026-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_forms_workflows",
            "0080_add_rating_matrix_address_slider_fields_and_form_controls",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="success_message",
            field=models.TextField(
                blank=True,
                help_text="Custom HTML shown after submission. Supports answer piping with {field_name} tokens that are replaced with the submitted values. Leave blank for the default confirmation message.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="success_redirect_rules",
            field=models.JSONField(
                blank=True,
                help_text='Conditional redirects based on form data. Format: [{"field": "field_name", "operator": "equals", "value": "...", "url": "https://..."}]. First matching rule wins; falls back to success_redirect_url or the default page.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="success_redirect_url",
            field=models.URLField(
                blank=True,
                help_text="Redirect to this URL after submission instead of showing a success page.",
            ),
        ),
    ]
