# Generated by Django 5.2.7 on 2026-04-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0081_add_success_page_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g. 'Approval Certificate', 'Offer Letter').",
                        max_length=200,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this template instead of the built-in PDF layout when downloading a submission PDF.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "html_content",
                    models.TextField(
                        help_text="Full HTML document with CSS. Use {field_name} merge fields to insert submitted values. Use {% if field_name %}...{% endif %} for conditional sections. Available variables: {form_name}, {submission_id}, {submitted_at}, {status}, {submitter_name}, and all form field names."
                    ),
                ),
                (
                    "page_size",
                    models.CharField(
                        choices=[
                            ("letter", "US Letter (8.5 x 11 in)"),
                            ("a4", "A4 (210 x 297 mm)"),
                            ("legal", "US Legal (8.5 x 14 in)"),
                        ],
                        default="letter",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_definition",
                    models.ForeignKey(
                        help_text="The form this template belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="django_forms_workflows.formdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "ordering": ["form_definition", "name"],
            },
        ),
    ]
