# Generated by Django 5.2.7 on 2026-04-01 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0083_workflowdefinition_start_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedOptionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g. 'Departments', 'Building Locations')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier used in the API and form builder",
                        unique=True,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        help_text='Ordered list of options. Each item is either a string (used as both value and label) or an object: {"value": "eng", "label": "Engineering"}.'
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive lists are hidden from the form builder but still resolve for existing fields.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shared Option List",
                "verbose_name_plural": "Shared Option Lists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="formfield",
            name="shared_option_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Use a centrally managed option list instead of inline choices. When set, this overrides the choices field above.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_fields",
                to="django_forms_workflows.sharedoptionlist",
            ),
        ),
    ]
