# Generated by Django 5.2.7 on 2026-04-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0084_add_shared_option_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="payment_amount_field",
            field=models.CharField(
                blank=True,
                help_text="field_name of a currency/decimal field for dynamic amounts.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_amount_type",
            field=models.CharField(
                blank=True,
                choices=[("fixed", "Fixed Amount"), ("field", "From Form Field")],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_currency",
            field=models.CharField(
                blank=True,
                default="usd",
                help_text="ISO 4217 currency code (e.g., 'usd', 'cad').",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_description_template",
            field=models.CharField(
                blank=True,
                help_text="Charge description. Supports {field_name} tokens.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_enabled",
            field=models.BooleanField(
                default=False, help_text="Require payment for form submission."
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed payment amount (when amount type is 'fixed').",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                help_text="Registered payment provider key (e.g., 'stripe').",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_payment", "Pending Payment"),
                    ("submitted", "Submitted"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=50)),
                (
                    "transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requires_action", "Requires Action"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("provider_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_records",
                        to="django_forms_workflows.formdefinition",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="django_forms_workflows.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Record",
                "verbose_name_plural": "Payment Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "status"],
                        name="django_form_submiss_d8e9e5_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="django_form_transac_44dbea_idx"
                    ),
                ],
            },
        ),
    ]
