# Generated by Django 5.2.7 on 2026-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0085_add_payment_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="embed_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow this form to be embedded on external websites via an iframe. The form is served at /forms/<slug>/embed/ with a minimal layout. Works best with requires_login=False forms.",
            ),
        ),
    ]
