# Generated by Django 5.2.7 on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0086_add_embed_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="use_triggering_stage",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When checked, automatically scopes this rule to whichever "
                    "stage triggered the event at runtime. This avoids needing "
                    "to create a separate rule per stage. Overrides the Stage "
                    "dropdown above."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional. When set, scopes this rule to a specific stage. "
                    "Recipient sources like 'Notify stage assignees' and "
                    "'Notify stage groups' will reference only this stage. "
                    "When blank, they reference all stages in the workflow. "
                    "Ignored when 'Use triggering stage' is checked."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_rules",
                to="django_forms_workflows.workflowstage",
            ),
        ),
    ]
