# Generated by Django 5.2.7 on 2026-04-02

from django.db import migrations, models


def create_default_notification_rules(apps, schema_editor):
    """Auto-create NotificationRule records for workflows that relied on
    the built-in send_approval_request and send_approval_reminder tasks.

    This ensures that removing the hardcoded email dispatch does not
    silently break existing workflows.
    """
    WorkflowDefinition = apps.get_model(
        "django_forms_workflows", "WorkflowDefinition"
    )
    NotificationRule = apps.get_model(
        "django_forms_workflows", "NotificationRule"
    )

    for wf in WorkflowDefinition.objects.all():
        # approval_request: replaces built-in send_approval_request
        if not NotificationRule.objects.filter(
            workflow=wf, event="approval_request"
        ).exists():
            NotificationRule.objects.create(
                workflow=wf,
                event="approval_request",
                use_triggering_stage=True,
                notify_stage_assignees=True,
                notify_stage_groups=True,
            )

        # approval_reminder: replaces built-in send_approval_reminder
        if (
            getattr(wf, "send_reminder_after_days", None)
            and not NotificationRule.objects.filter(
                workflow=wf, event="approval_reminder"
            ).exists()
        ):
            NotificationRule.objects.create(
                workflow=wf,
                event="approval_reminder",
                use_triggering_stage=True,
                notify_stage_assignees=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0087_notificationrule_use_triggering_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="body_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Custom email body (HTML). Rendered as a Django template with "
                    "the full notification context (submission, form_data, approver, "
                    "task, approval_url, submission_url, site_name, etc.). "
                    "Leave blank to use the built-in template for this event type."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="event",
            field=models.CharField(
                choices=[
                    ("submission_received", "Submission Received"),
                    ("approval_request", "Approval Request (stage activated)"),
                    ("stage_decision", "Stage Decision (individual stage completed)"),
                    ("workflow_approved", "Workflow Approved (final decision)"),
                    ("workflow_denied", "Workflow Denied (final decision)"),
                    ("form_withdrawn", "Form Withdrawn"),
                    ("approval_reminder", "Approval Reminder"),
                    ("escalation", "Escalation"),
                ],
                help_text="The workflow event that triggers this notification.",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            create_default_notification_rules,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
