# Generated by Django 6.0.3 on 2026-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_forms_workflows", "0088_notificationrule_body_template_and_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="hide_comment_field",
            field=models.BooleanField(
                default=False,
                help_text="Hide the public decision comment field from approvers at this stage. Useful for stages where no notifications are sent to the submitter or where the comment would not be meaningful.",
            ),
        ),
    ]
