# Generated by Django 5.2.7 on 2026-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_forms_workflows", "0089_workflowstage_hide_comment_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageapprovalgroup",
            options={
                "ordering": ["role", "position"],
                "verbose_name": "Stage Approval Group",
                "verbose_name_plural": "Stage Approval Groups",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stageapprovalgroup",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stageapprovalgroup",
            name="role",
            field=models.CharField(
                choices=[
                    ("approval", "Approval (default)"),
                    ("validation", "Assignee validation"),
                    ("reassignment", "Reassignment pool"),
                ],
                default="approval",
                help_text="Purpose of this group in the stage. 'Approval' groups receive fallback tasks and define the default pool. 'Validation' groups are checked when verifying a dynamic assignee's group membership (falls back to approval groups when none defined). 'Reassignment' groups define who may be reassigned to (falls back to approval groups when none defined).",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stageapprovalgroup",
            unique_together={("stage", "group", "role")},
        ),
    ]
